# Generated by Django 3.1.2 on 2021-01-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mywebblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, unique=True)),
                ('wblog', models.TextField()),
                ('createtime', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-createtime'],
            },
        ),
    ]
