# Generated by Django 3.1.2 on 2021-01-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mywebblog',
            options={},
        ),
    ]
