# Generated by Django 3.1.2 on 2021-01-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210107_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywebblog',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
